<?php $data = $block->getCustomer(); ?>
<div class="block">
    <div class="block-content">
        <div class="box">
            <div class="box-content">
                <p><strong>Avatar:</strong></p>
                <div><img src="<?php $url = $block->getBaseUrl(); echo $url.'pub/media/customer'.$data['Avatar'] ?>" width="250px" height="250px" ></div>
                <p><strong>Name</strong>: <?php echo $data['Name'] ?></p>
                <p><strong>Email</strong>: <?php echo $data['Email'] ?></p>
                <p><strong>Phone</strong>: <?php echo $data['Phone'] ?></p>
            </div>
        </div>
    </div>
</div>