<input value="Open Modal" type="button" name="open_modal" id="open_modal">&emsp;
<input value="Open Magento Login Modal" type="button" name="open_magento_login_modal">&emsp;
<input value="Open Custom Login Modal" type="button" name="open_custom_login_modal">

<div id="popup-form" class="shadow-div" style="display: none; width: 500px;margin: 50px auto;background-color: white">
    <div class="form-login" style="width: 400px;margin: auto;">
        <p>
            <label for="namelogin">Name</label>
            <input type="text" name="namelogin" id="namelogin"><br>
        </p>
        <p>
            <label for="passlogin">Password</label>
            <input type="password" name="passlogin" id="passlogin"><br>
        </p>
        <button class="ok_button">Login</button><br>
        <p><span style="color: darkgray;font-size: small;">Not registered</span> <a href="#" style="color: lightblue;font-size: small;">Create an account</a></p>
    </div>
</div>